//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logger
    {
        public long Id { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Exception { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
